version: 2
registries:
  github:
    type: git
    url: https://github.com
    username: ${{secrets.EXTERNAL_GITHUB_USER}}
    password: ${{secrets.EXTERNAL_GITHUB_TOKEN}}

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    registries:
      - github
    schedule:
      interval: "daily"
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: chore
      include: scope

