name: build
on: [push, pull_request, merge_group]

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker context for Buildx
      id: buildx-context
      run: |
        docker context create builders

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        version: latest
        endpoint: builders

    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v4

    - name: Build images
      id: buildimages
      run: |
        img=ghcr.io/${{github.repository}}:${{github.sha}}
        echo "IMAGE_NAME=${img} >> $GITHUB_OUTPUT"
        docker pull ${img} || (
          docker buildx build --push --cache-to type=gha,mode=max --cache-from type=gha --progress plain --platform linux/arm64/v8,linux/amd64 --build-arg BUILDKIT_INLINE_CACHE=1 -t ${img}  .
        )

    - name: Build main image images
      id: buildmainimage
      if: ${{ github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
      run: |
        img=ghcr.io/${{github.repository}}:latest
        echo "IMAGE_NAME=${img} >> $GITHUB_OUTPUT"
        docker buildx build --push --cache-to type=gha,mode=max --cache-from type=gha --progress plain --platform linux/arm64/v8,linux/amd64 --build-arg BUILDKIT_INLINE_CACHE=1 -t ${img}  .
