name: golangci-lint
on:
  push:
    branches:
      - main
      - master
  pull_request:
  merge_group:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.4'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v1.60.3
